PACKAGE_NAME="t1bridge-dkms"
PACKAGE_VERSION="0.1.8"

MAKE[0]="make -C kernel/dkms KDIR=/lib/modules/${kernelver}/build"

BUILT_MODULE_NAME[0]="t1_cfgsel"
BUILT_MODULE_LOCATION[0]="kernel/t1-cfgsel"
DEST_MODULE_LOCATION[0]="/updates/dkms"

BUILT_MODULE_NAME[1]="appletbdrm"
BUILT_MODULE_LOCATION[1]="kernel/appletbdrm-t1"
DEST_MODULE_LOCATION[1]="/updates/dkms"

BUILT_MODULE_NAME[2]="apple_t1_ncm"
BUILT_MODULE_LOCATION[2]="kernel/apple-t1-ncm"
DEST_MODULE_LOCATION[2]="/updates/dkms"

BUILT_MODULE_NAME[3]="uvcvideo"
BUILT_MODULE_LOCATION[3]="kernel/uvcvideo-t1"
DEST_MODULE_LOCATION[3]="/updates/dkms"

AUTOINSTALL="yes"
